.phony : all, build, slide, frankln, web, trace, clean

OS:=$(shell uname -s)

all: build

build:
	rm -f Manifest.toml
	docker-compose build
	docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'

slide:
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("remark/example.jl","remark")'

franklin:
	# serve web page without creating slide generated by Remark.jl
	docker-compose up franklin

web:
	# serve web page including creating slide generated by Remark.jl
	docker-compose up web

trace: clean
	docker run --rm -it -v ${PWD}:/work -w /work julia:1.4.1 julia --trace-compile=./.statements/franklin.jl --project=@. -e 'using Pkg; Pkg.instantiate(); using Franklin; serve()'
clean:
	docker-compose down
	rm -f  Manifest.toml # reset Manifest.toml
	rm -rf remark/src remark/build # assets generated by Remark.jl
	rm -rf __site # assets generated by Franklin.jl
