.phony : all, pull build, slide, frankln, web, trace, clean

OS:=$(shell uname -s)

OS:=$(shell uname -s)
DOCKERIMAGE=mathseminarjl

ifeq ($(OS), Linux)
TAG=latest
REMOTE_DOCKER_REPOSITORY:=terasakisatoshi/${DOCKERIMAGE}:${TAG}
endif
ifeq ($(OS), Darwin)
TAG=latest
REMOTE_DOCKER_REPOSITORY:=terasakisatoshi/${DOCKERIMAGE}:${TAG}
endif


all: build

pull:
	rm -f Manifest.toml
	docker pull ${REMOTE_DOCKER_REPOSITORY}
	docker tag ${REMOTE_DOCKER_REPOSITORY} mathseminarjl
	docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'

build:
	rm -f Manifest.toml
	docker build -t mathseminarjl .
	docker-compose build
	docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'

slide:
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/remark", options = Dict("ratio" => "16:9"), title = "Remark.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/franklin", options = Dict("ratio" => "16:9"), title = "Franklin.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/dash", options = Dict("ratio" => "16:9"), title = "Dash.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/binarybuilder", options = Dict("ratio" => "16:9"), title = "BinaryBuilder.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/myworkflow", options = Dict("ratio" => "16:9"), title = "MyWorkflow.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/repl", options = Dict("ratio" => "16:9"), title = "Do something great in your REPL")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/intro2julia", options = Dict("ratio" => "16:9"), title = "Intro2Julia")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/pycallchainrules", options = Dict("ratio" => "16:9"), title = "PyCallChainRules.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/replay", options = Dict("ratio" => "16:9"), title = "Replay.jl")'
	docker-compose run --rm julia julia -e 'using Remark; Remark.slideshow("./slideshow/pluto", options = Dict("ratio" => "16:9"), title = "Intro to Pluto.jl")'

franklin:
	# serve web page without creating slide generated by Remark.jl
	docker-compose up franklin

web:
	# serve web page including creating slide generated by Remark.jl
	docker-compose run --rm web

clean:
	docker-compose down
	rm -f  Manifest.toml # reset Manifest.toml
	rm -rf slideshow/src slideshow/build # assets generated by Remark.jl
	rm -rf __site # assets generated by Franklin.jl
