name: Build-Push
on:
  schedule:
    - cron: 0 3 * * *
  push:
    branches:
      - master

jobs:
  build-container:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: terasakisatoshi/mathseminarjl
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
