name: CI with Docker
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GKSwstype: 100
      JULIA_NUM_THREADS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: mathseminarjl
	push_image_and_stages: false
    - run: docker build -t mathseminarjl .
    - run: docker-compose build julia
    - run: docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'
    - run: docker-compose run --rm julia julia /work/_mytools/deploy.jl
