name: CI with Docker
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GKSwstype: 100
      JULIA_NUM_THREADS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: terasakisatoshi
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: terasakisatoshi/mathseminarjl
        push_image_and_stages: false
    - run: docker build --cache-from terasakisatoshi/mathseminarjl -t mathseminarjl .
    - run: docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'
    - run: docker-compose run --rm julia julia /work/_mytools/deploy.jl
