name: Docker
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - run: docker-compose build julia
    - run: docker-compose run --rm julia julia -e 'using Pkg; Pkg.instantiate()'
    - run: docker-compose run --rm julia julia /work/_mytools/deploy.jl