name: CI-no-docker
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GKSwstype: 100
      JULIA_NUM_THREADS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - run: julia --project=@. -e 'using Pkg; Pkg.add(["NodeJS", "Franklin", "Literate", "Remark", "Weave"])'
    - run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
    - run: julia --project=@. ./_mytools/deploy.jl
